### ISSUE TITLE
privileges in postgresql_grant will be missing after a period of time

### ISSUE THREAD

**Issue by acmicrox** [cyrilgdn/terraform-provider-postgresql#141]
Hi,

We encountered a strange issue that the privilege in postgresql_grant will be missing after a period of time (like about one day). This issue won't happen when you run `terraform apply` consecutively in a short period of time (several hours is fine). 
Any comment is appreciated. Thanks.

### Terraform Version
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.14.0
+ provider registry.terraform.io/hashicorp/google v3.85.0
+ provider registry.terraform.io/hashicorp/vault v2.22.1

Your version of Terraform is out of date! The latest version
is 1.0.7. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)
- postgresql_grant

### Terraform Configuration Files
```hcl
resource "postgresql_grant" "user-privileges" {
  database    = "database_name"
  role             = "database_user"
  schema      = "public"
  object_type = "table"
  privileges  = ["SELECT"]
}
```

### Expected Behavior
After I run `terraform apply` and don't make any change in the config file, it shall show `No changes. Your infrastructure matches the configuration` next time when I rerun `terraform apply` .

### Actual Behavior
When `terraform apply` is run twice in a short period of time, everything is fine. However, the interval between the first and the second `terraform apply` is longer than some duration. `terraform plan` will show the `"SELECT" privilege is missing (red hyphen)` and `the resource `postgresql_grant.user-privileges` has been changed` like below

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

# postgresql_grant.user-privileges has been changed
  ~ resource "postgresql_grant" "user-privileges" {
        id                = "database_name_public_table"
      ~ privileges        = [
          - "SELECT",
        ]
        # (5 unchanged attributes hidden)
    }
```

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. wait a period of time (probably one day)
5. `terraform init`
6. `terraform plan`

### Important Factoids
The postgresql db instance is on GCP

**Comment by alec-rabold** [comment]
I believe this happens when there's new tables created after the`postgresql_grant` resource is applied. When you create a new table then run `terraform apply` there's a diff in the role's permissions.

You may look into `postgresql_default_privileges` as that should give the role permissions to any future objects, whereas `postgresql_grant` only provides access to objects that exist at `apply` time.

**Comment by acmicrox** [comment]
@alec-rabold Thanks for your reply. We do have new partition tables created on a daily basis. Because the user still can run select query from new database, we don't find there exists such a diff.

I try to use `postgresql_default_privileges` like below. However, the role can log in but can't do select queries on existing tables. Can you kindly let me know what's wrong with my setting? I can't find more info from the doc. Many thanks.
```
resource "postgresql_role" "test_role" {
  name     = "test_role"
  login    = "true"
  password = "test_role"
}

resource "postgresql_default_privileges" "test_role_privilege" {
  role     = "test_role"
  database = "db_name"
  schema   = "public"

  owner       = "cloudsqlsuperuser"
  object_type = "table"
  privileges  = ["SELECT"]
}
```

**Comment by alec-rabold** [comment]
Ah in that case, the partition tables would maintain their own permission sets (separately from the table that it sounds like your user is querying). You should be able to verify this by having the user query the partition table directly rather than the main table. They should get `permission denied for table foo_partition`, but still be able to get the corresponding data from the main table `foo`.

For `postgresql_default_privileges`, ideally it would be applied at the same time the database itself is created (before any tables or other objects exist). But if that's not possible I believe you could either:
* Use the `postgresql_default_privileges` snippet you provided, which would grant `SELECT` permissions on `ALL` _future_ `TABLES` (but not existing). Then you could manually issue a one-time statement to account for the existing tables: 
```SQL
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO cfs_power_user
```
* Or, use your `postgresql_default_privileges` snippet alongside your original `postgresql_grant`, accepting that you'll have a perpetual Terraform diff. The diff will practically be a no-op though.
```HCL
resource "postgresql_grant" "user-privileges" {
  database    = "database_name"
  role             = "database_user"
  schema      = "public"
  object_type = "table"
  privileges  = ["SELECT"]
}
```

Also keep in mind that if you have multiple users/roles creating the tables, then you'd need multiple `default_privileges` resources - one for each `owner`.

Hope that helps!

**Comment by acmicrox** [comment]
@alec-rabold Thanks for the explanation. It's strange that the user can SELECT on the new partitioned table without `terraform apply`. I checked the privilege with the SQL below. I did find that the original user has the `SELECT` privilege. Anyway, since my questions were answered, I'd like to close this issue. Many thanks for your kind help.

```
SELECT grantee, privilege_type FROM information_schema.role_table_grants WHERE table_name='<partitioned_table>';
```

**Comment by Josh-a-e** [comment]
> Ah in that case, the partition tables would maintain their own permission sets (separately from the table that it sounds like your user is querying). You should be able to verify this by having the user query the partition table directly rather than the main table. They should get `permission denied for table foo_partition`, but still be able to get the corresponding data from the main table `foo`.
> 
> For `postgresql_default_privileges`, ideally it would be applied at the same time the database itself is created (before any tables or other objects exist). But if that's not possible I believe you could either:
> 
> * Use the `postgresql_default_privileges` snippet you provided, which would grant `SELECT` permissions on `ALL` _future_ `TABLES` (but not existing). Then you could manually issue a one-time statement to account for the existing tables:
> 
> ```sql
> GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO test_role;
> ```
> 
> * Or, use your `postgresql_default_privileges` snippet alongside your original `postgresql_grant`, accepting that you'll have a Terraform diff whenever new tables are created. The diff will practically be a no-op though.
> 
> ```terraform
> resource "postgresql_grant" "user-privileges" {
>   database    = "db_name"
>   role        = "test_role"
>   schema      = "public"
>   object_type = "table"
>   privileges  = ["SELECT"]
> }
> ```
> 
> Also keep in mind that if you have multiple users/roles creating the tables, then you'd need multiple `default_privileges` resources - one for each `owner`.
> 
> Hope that helps!

IMO this belongs in the docs, but I'm glad I found this - thanks!
