### ISSUE TITLE
How to define tables and fields ?

### ISSUE THREAD

**Issue by PierreAdrienDelisle** [cyrilgdn/terraform-provider-postgresql#17]
Hi there,
I'm currently using your solution and thank you for that.
I'm able to connect to a RDS instance of PostgreSQL and to create role, db or schema. 

But I kind of struggle to understand how to define tables and fields here.
Is it something not supported ? Or maybe something I misunderstood in your solution.

If not, do you have any piece of advice on how to achieve that please?

**Comment by SN9NV** [comment]
Hi. I don't think Terraform is a good way to manage the schema off the database. I would recommend using a tool designed for schema migration.

The reason I say Terraform is not good for this is because you can't define a series of table changes at the same time and you can't define a script to transform the data if you need to change the schema for every change. A database schema is something very complicated and it's not something that Terraform can handle IMO. If a table changes, you can't just drop the table and make a new one, the data will be gone. I believe you should use a dedicated tool for managing the schema.

**Comment by PierreAdrienDelisle** [comment]
Thank you for your knowledge @SN9NV , I asked a colleague of mine and said the same thing so I'll head towards that solution of using a migration tool. 
For people having the same issue, I post some solutions I found :
 - I'm heading towards this migration tool: [golang migrate]( https://github.com/golang-migrate/migrate) designed for Go like my current project.
 - I heard SQLAlchemy for python is nice also if your project is in that language
