### ISSUE TITLE
No data sources exist

### ISSUE THREAD

**Issue by mbrancato** [cyrilgdn/terraform-provider-postgresql#181]
I noticed there are no data sources for the provider. Something like this seems useful:

```hcl
data "postgresql_database" "my_db" {
  name = "my_db"
}

resource "postgresql_grant" "my_grant" {
  database    = data.postgresql_database.my_db.name
  role        = "test_role"
  schema      = "public"
  object_type = "table"
  privileges  = ["SELECT"]
}
```

This is useful for referencing resources that TF didn't create or shouldn't delete. Has this been considered or determined to not work? I couldn't find any previous issues. Its also very helpful in some logic around bootstrapping complex systems where spinning up the DB instance happens with TF, then some tool or software creates some initial DB and tables, and then afterwards you need to apply additional grants or similar changes using TF again.

**Comment by cyrilgdn** [comment]
Hi @mbrancato ,

Thanks for opening the issue and sorry for the response delay.

We could add some datasources (there's an open PR to retrieve list of schemas for example: #171).

But in your example, I don't see the point to create a data sources to retrieve a database by its name in order to get its name. Better use the name directly in the `postgresql_grant` resource of use a local variable for that if you don't want to hardcode it in multiple places. 

If you have other needs, you can explain them and we could see if we could do it.

**Comment by kevinmichaelchen** [comment]
Is there a way to dynamically retrieve the cluster's endpoint / hostname?

**Comment by cyrilgdn** [comment]
Without any response from the author, I close this issue. But feel free to open it back if needed.

@kevinmichaelchen I don't think it's the role of Postgres (so even less of the TF provider) to know where is it reachable as it depends on how you deploy it. 
More than that you need to configure it in the provider so it can connect to the instance, so you already have it :sweat_smile: . But maybe I misunderstood your question ?
