### ISSUE TITLE
terraform-bundle does not find release version

### ISSUE THREAD

**Issue by luizfelipefb** [cyrilgdn/terraform-provider-postgresql#50]
Running the command `terraform-bundle package -os=linux -arch=amd64 terraform-bundle.hcl` does not fetch the provider.

### Terraform Version
- 0.12.29

### Affected Resource(s)
- provider

### Terraform Configuration Files
```hcl
terraform {
  version = "0.12.29"
}

providers {
  postgresql = ["1.11.1"]
}

```

### Debug Output
```
- Resolving "postgresql" provider (1.11.1)...
- Checking for provider plugin on https://releases.hashicorp.com...
- Failed to resolve postgresql provider 1.11.1: unable to verify signature
The command '/bin/sh -c terraform-bundle package -os=linux -arch=amd64 terraform-bundle.hcl' returned a non-zero code: 1
```

### Expected Behavior
Install the provider plugin

### Actual Behavior
Failed to resolve postgresql provider 1.11.1

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create the terraform-bundle.hcl files as described above
1. Run the command `terraform-bundle package -os=linux -arch=amd64 terraform-bundle.hcl`

**Comment by cyrilgdn** [comment]
Hi @luizfelipefb ,

Since Terraform 0.13 and the new [registry](https://registry.terraform.io/), `postgresql` provider (like all community providers) is not officially hosted by Hashicorp anymore so new versions can't be installed like that.

Your choices are:
* Upgrade to Terraform 0.13 or more and use the new registry compatible syntax:
```hcl
terraform {
  version = "0.13.6"
}

providers {
  postgresql = {
    versions = ["1.11.1"]
    source   = "cyrilgdn/postgresql"
  }
}
```

* Use the last Hashicorp hosted version for Terraform0.12 (1.7.1)
```hcl
terraform {
  version = "0.12.29"
}

providers {
  postgresql = ["1.7.1"]
}
```
* Download manually the [version](https://github.com/cyrilgdn/terraform-provider-postgresql/releases/tag/v1.11.1) you want and put it in the plugins directory before bundle (cf [custom plugin example in `terraform-bundle` doc](https://github.com/hashicorp/terraform/tree/v0.12.29/tools/terraform-bundle#usage))
